var _async_uni_task_void_method_builder_8cs =
[
    [ "Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_void_method_builder.html", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_void_method_builder" ]
];