var _sprite_swap_transitions_8cs =
[
    [ "CORE.Shared.UI.Custom.State.SpriteSwapTransitions", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_sprite_swap_transitions.html", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_sprite_swap_transitions" ],
    [ "CORE.Shared.UI.Custom.State.SpriteSwapTransitions.SpriteSwapTransitionState", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_sprite_swap_transitions_1_1_sprite_swap_transition_state.html", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_sprite_swap_transitions_1_1_sprite_swap_transition_state" ]
];