var _transition_state_collection_8cs =
[
    [ "CORE.Shared.UI.Custom.State.TransitionStateCollection", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_transition_state_collection.html", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_transition_state_collection" ],
    [ "CORE.Shared.UI.Custom.State.TransitionStateCollection.TransitionStateBase", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_transition_state_collection_1_1_transition_state_base.html", "class_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_state_1_1_transition_state_collection_1_1_transition_state_base" ]
];