var _unity_async_extensions_8u_g_u_i_8cs =
[
    [ "Cysharp.Threading.Tasks.UnityAsyncExtensions", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_async_extensions.html", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_async_extensions" ],
    [ "Cysharp.Threading.Tasks.IAsyncClickEventHandler", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_click_event_handler.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_click_event_handler" ],
    [ "Cysharp.Threading.Tasks.IAsyncValueChangedEventHandler< T >", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_value_changed_event_handler-1-g.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_value_changed_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.IAsyncEndEditEventHandler< T >", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_end_edit_event_handler-1-g.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_end_edit_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.IAsyncEndTextSelectionEventHandler< T >", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_end_text_selection_event_handler-1-g.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_end_text_selection_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.IAsyncTextSelectionEventHandler< T >", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_text_selection_event_handler-1-g.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_text_selection_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.IAsyncDeselectEventHandler< T >", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_deselect_event_handler-1-g.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_deselect_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.IAsyncSelectEventHandler< T >", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_select_event_handler-1-g.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_select_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.IAsyncSubmitEventHandler< T >", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_submit_event_handler-1-g.html", "interface_cysharp_1_1_threading_1_1_tasks_1_1_i_async_submit_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.AsyncUnityEventHandler", "class_cysharp_1_1_threading_1_1_tasks_1_1_async_unity_event_handler.html", "class_cysharp_1_1_threading_1_1_tasks_1_1_async_unity_event_handler" ],
    [ "Cysharp.Threading.Tasks.AsyncUnityEventHandler< T >", "class_cysharp_1_1_threading_1_1_tasks_1_1_async_unity_event_handler-1-g.html", "class_cysharp_1_1_threading_1_1_tasks_1_1_async_unity_event_handler-1-g" ],
    [ "Cysharp.Threading.Tasks.UnityEventHandlerAsyncEnumerable", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_event_handler_async_enumerable.html", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_event_handler_async_enumerable" ],
    [ "Cysharp.Threading.Tasks.UnityEventHandlerAsyncEnumerable.UnityEventHandlerAsyncEnumerator", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_event_handler_async_enumerable_1_1_unity_event_handler_async_enumerator.html", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_event_handler_async_enumerable_1_1_unity_event_handler_async_enumerator" ],
    [ "Cysharp.Threading.Tasks.UnityEventHandlerAsyncEnumerable< T >", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_event_handler_async_enumerable-1-g.html", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_event_handler_async_enumerable-1-g" ],
    [ "Cysharp.Threading.Tasks.UnityEventHandlerAsyncEnumerable< T >.UnityEventHandlerAsyncEnumerator", "class_cysharp_1_1_threading_1_1_tasks_1_1_unity_event_handler_async_enumerable-1-g_1_1_unity_event_handler_async_enumerator.html", null ]
];