var dir_d6f8d660d37b2518beab2cd4019cc7fc =
[
    [ "Utilities", "dir_c7bb994976721aabe93fd8eaf4d7d956.html", "dir_c7bb994976721aabe93fd8eaf4d7d956" ],
    [ "AssemblyInfo.cs", "_third_party_2_localization_2_runtime_2_assembly_info_8cs.html", null ],
    [ "Language.cs", "_language_8cs.html", "_language_8cs" ],
    [ "LocaleItem.cs", "_locale_item_8cs.html", "_locale_item_8cs" ],
    [ "LocaleItemBase.cs", "_locale_item_base_8cs.html", "_locale_item_base_8cs" ],
    [ "Localization.cs", "_localization_8cs.html", "_localization_8cs" ],
    [ "LocalizationPrefs.cs", "_localization_prefs_8cs.html", "_localization_prefs_8cs" ],
    [ "LocalizationSettings.cs", "_localization_settings_8cs.html", "_localization_settings_8cs" ],
    [ "LocalizedAsset.cs", "_localized_asset_8cs.html", "_localized_asset_8cs" ],
    [ "LocalizedAssetBase.cs", "_localized_asset_base_8cs.html", "_localized_asset_base_8cs" ],
    [ "LocalizedAssetBehaviour.cs", "_localized_asset_behaviour_8cs.html", "_localized_asset_behaviour_8cs" ],
    [ "LocalizedAudioClip.cs", "_localized_audio_clip_8cs.html", "_localized_audio_clip_8cs" ],
    [ "LocalizedAudioClipBehaviour.cs", "_localized_audio_clip_behaviour_8cs.html", "_localized_audio_clip_behaviour_8cs" ],
    [ "LocalizedFont.cs", "_localized_font_8cs.html", "_localized_font_8cs" ],
    [ "LocalizedFontBehaviour.cs", "_localized_font_behaviour_8cs.html", "_localized_font_behaviour_8cs" ],
    [ "LocalizedGenericAssetBehaviour.cs", "_localized_generic_asset_behaviour_8cs.html", "_localized_generic_asset_behaviour_8cs" ],
    [ "LocalizedGenericAssetBehaviourBase.cs", "_localized_generic_asset_behaviour_base_8cs.html", "_localized_generic_asset_behaviour_base_8cs" ],
    [ "LocalizedMaterialBehaviour.cs", "_localized_material_behaviour_8cs.html", "_localized_material_behaviour_8cs" ],
    [ "LocalizedPrefab.cs", "_localized_prefab_8cs.html", "_localized_prefab_8cs" ],
    [ "LocalizedPrefabBehaviour.cs", "_localized_prefab_behaviour_8cs.html", "_localized_prefab_behaviour_8cs" ],
    [ "LocalizedRendererBehaviour.cs", "_localized_renderer_behaviour_8cs.html", "_localized_renderer_behaviour_8cs" ],
    [ "LocalizedSprite.cs", "_localized_sprite_8cs.html", "_localized_sprite_8cs" ],
    [ "LocalizedSpriteBehaviour.cs", "_localized_sprite_behaviour_8cs.html", "_localized_sprite_behaviour_8cs" ],
    [ "LocalizedText.cs", "_localized_text_8cs.html", "_localized_text_8cs" ],
    [ "LocalizedTextAsset.cs", "_localized_text_asset_8cs.html", "_localized_text_asset_8cs" ],
    [ "LocalizedTextAssetBehaviour.cs", "_localized_text_asset_behaviour_8cs.html", "_localized_text_asset_behaviour_8cs" ],
    [ "LocalizedTextBehaviour.cs", "_localized_text_behaviour_8cs.html", "_localized_text_behaviour_8cs" ],
    [ "LocalizedTexture.cs", "_localized_texture_8cs.html", "_localized_texture_8cs" ],
    [ "LocalizedTextureBehaviour.cs", "_localized_texture_behaviour_8cs.html", "_localized_texture_behaviour_8cs" ],
    [ "LocalizedVideoClip.cs", "_localized_video_clip_8cs.html", "_localized_video_clip_8cs" ],
    [ "LocalizedVideoClipBehaviour.cs", "_localized_video_clip_behaviour_8cs.html", "_localized_video_clip_behaviour_8cs" ]
];