var interface_cysharp_1_1_threading_1_1_tasks_1_1_triggers_1_1_i_async_on_transform_parent_changed_handler =
[
    [ "OnTransformParentChangedAsync", "interface_cysharp_1_1_threading_1_1_tasks_1_1_triggers_1_1_i_async_on_transform_parent_changed_handler.html#ae8a4aab684ec77dd0dcbf0dee985f0aa", null ]
];