var interface_cysharp_1_1_threading_1_1_tasks_1_1_triggers_1_1_i_async_on_pointer_click_handler =
[
    [ "OnPointerClickAsync", "interface_cysharp_1_1_threading_1_1_tasks_1_1_triggers_1_1_i_async_on_pointer_click_handler.html#abd7f6aead3cabf530eded9f43aac79df", null ]
];