var namespace_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_interfaces =
[
    [ "ICustomTransitionUiElement", "interface_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_interfaces_1_1_i_custom_transition_ui_element.html", "interface_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_interfaces_1_1_i_custom_transition_ui_element" ],
    [ "IImageAppearanceProvider", "interface_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_interfaces_1_1_i_image_appearance_provider.html", "interface_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_interfaces_1_1_i_image_appearance_provider" ],
    [ "IMaskableHelper", "interface_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_interfaces_1_1_i_maskable_helper.html", "interface_c_o_r_e_1_1_shared_1_1_u_i_1_1_custom_1_1_interfaces_1_1_i_maskable_helper" ]
];