var namespace_c_o_r_e_1_1_shared_1_1_generated_1_1_localization =
[
    [ "LocalizationTextGenerated", "class_c_o_r_e_1_1_shared_1_1_generated_1_1_localization_1_1_localization_text_generated.html", "class_c_o_r_e_1_1_shared_1_1_generated_1_1_localization_1_1_localization_text_generated" ]
];