var namespace_game_toolkit_1_1_localization =
[
    [ "Editor", "namespace_game_toolkit_1_1_localization_1_1_editor.html", "namespace_game_toolkit_1_1_localization_1_1_editor" ],
    [ "Tests", "namespace_game_toolkit_1_1_localization_1_1_tests.html", "namespace_game_toolkit_1_1_localization_1_1_tests" ],
    [ "Utilities", "namespace_game_toolkit_1_1_localization_1_1_utilities.html", "namespace_game_toolkit_1_1_localization_1_1_utilities" ],
    [ "Language", "class_game_toolkit_1_1_localization_1_1_language.html", "class_game_toolkit_1_1_localization_1_1_language" ],
    [ "LocaleChangedEventArgs", "class_game_toolkit_1_1_localization_1_1_locale_changed_event_args.html", "class_game_toolkit_1_1_localization_1_1_locale_changed_event_args" ],
    [ "LocaleItem< T >", "class_game_toolkit_1_1_localization_1_1_locale_item-1-g.html", "class_game_toolkit_1_1_localization_1_1_locale_item-1-g" ],
    [ "LocaleItemBase", "class_game_toolkit_1_1_localization_1_1_locale_item_base.html", "class_game_toolkit_1_1_localization_1_1_locale_item_base" ],
    [ "Localization", "class_game_toolkit_1_1_localization_1_1_localization.html", "class_game_toolkit_1_1_localization_1_1_localization" ],
    [ "LocalizationPrefs", "class_game_toolkit_1_1_localization_1_1_localization_prefs.html", "class_game_toolkit_1_1_localization_1_1_localization_prefs" ],
    [ "LocalizationSettings", "class_game_toolkit_1_1_localization_1_1_localization_settings.html", "class_game_toolkit_1_1_localization_1_1_localization_settings" ],
    [ "LocalizedAsset< T >", "class_game_toolkit_1_1_localization_1_1_localized_asset-1-g.html", "class_game_toolkit_1_1_localization_1_1_localized_asset-1-g" ],
    [ "LocalizedAssetBase", "class_game_toolkit_1_1_localization_1_1_localized_asset_base.html", "class_game_toolkit_1_1_localization_1_1_localized_asset_base" ],
    [ "LocalizedAssetBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_asset_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_asset_behaviour" ],
    [ "LocalizedAudioClip", "class_game_toolkit_1_1_localization_1_1_localized_audio_clip.html", "class_game_toolkit_1_1_localization_1_1_localized_audio_clip" ],
    [ "LocalizedAudioClipBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_audio_clip_behaviour.html", null ],
    [ "LocalizedFont", "class_game_toolkit_1_1_localization_1_1_localized_font.html", "class_game_toolkit_1_1_localization_1_1_localized_font" ],
    [ "LocalizedFontBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_font_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_font_behaviour" ],
    [ "LocalizedGenericAssetBehaviour< TLocalizedAsset, T >", "class_game_toolkit_1_1_localization_1_1_localized_generic_asset_behaviour-2-g.html", "class_game_toolkit_1_1_localization_1_1_localized_generic_asset_behaviour-2-g" ],
    [ "LocalizedGenericAssetBehaviourBase", "class_game_toolkit_1_1_localization_1_1_localized_generic_asset_behaviour_base.html", "class_game_toolkit_1_1_localization_1_1_localized_generic_asset_behaviour_base" ],
    [ "LocalizedMaterialBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_material_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_material_behaviour" ],
    [ "LocalizedPrefab", "class_game_toolkit_1_1_localization_1_1_localized_prefab.html", "class_game_toolkit_1_1_localization_1_1_localized_prefab" ],
    [ "LocalizedPrefabBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_prefab_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_prefab_behaviour" ],
    [ "LocalizedRendererBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_renderer_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_renderer_behaviour" ],
    [ "LocalizedSprite", "class_game_toolkit_1_1_localization_1_1_localized_sprite.html", "class_game_toolkit_1_1_localization_1_1_localized_sprite" ],
    [ "LocalizedSpriteBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_sprite_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_sprite_behaviour" ],
    [ "LocalizedText", "class_game_toolkit_1_1_localization_1_1_localized_text.html", "class_game_toolkit_1_1_localization_1_1_localized_text" ],
    [ "LocalizedTextAsset", "class_game_toolkit_1_1_localization_1_1_localized_text_asset.html", "class_game_toolkit_1_1_localization_1_1_localized_text_asset" ],
    [ "LocalizedTextAssetBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_text_asset_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_text_asset_behaviour" ],
    [ "LocalizedTextBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_text_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_text_behaviour" ],
    [ "LocalizedTexture", "class_game_toolkit_1_1_localization_1_1_localized_texture.html", "class_game_toolkit_1_1_localization_1_1_localized_texture" ],
    [ "LocalizedTextureBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_texture_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_texture_behaviour" ],
    [ "LocalizedVideoClip", "class_game_toolkit_1_1_localization_1_1_localized_video_clip.html", "class_game_toolkit_1_1_localization_1_1_localized_video_clip" ],
    [ "LocalizedVideoClipBehaviour", "class_game_toolkit_1_1_localization_1_1_localized_video_clip_behaviour.html", "class_game_toolkit_1_1_localization_1_1_localized_video_clip_behaviour" ]
];