var namespace_c_o_r_e_1_1_shared_1_1_configs_1_1_settings_1_1_data =
[
    [ "ControlInputSetting", "class_c_o_r_e_1_1_shared_1_1_configs_1_1_settings_1_1_data_1_1_control_input_setting.html", "class_c_o_r_e_1_1_shared_1_1_configs_1_1_settings_1_1_data_1_1_control_input_setting" ],
    [ "QualityPresetSetting", "class_c_o_r_e_1_1_shared_1_1_configs_1_1_settings_1_1_data_1_1_quality_preset_setting.html", "class_c_o_r_e_1_1_shared_1_1_configs_1_1_settings_1_1_data_1_1_quality_preset_setting" ],
    [ "SettingsSettingBase", "class_c_o_r_e_1_1_shared_1_1_configs_1_1_settings_1_1_data_1_1_settings_setting_base.html", "class_c_o_r_e_1_1_shared_1_1_configs_1_1_settings_1_1_data_1_1_settings_setting_base" ]
];