var namespace_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services =
[
    [ "AsyncUniTaskMethodBuilder", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_method_builder.html", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_method_builder" ],
    [ "AsyncUniTaskMethodBuilder< T >", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_method_builder-1-g.html", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_method_builder-1-g" ],
    [ "AsyncUniTaskVoidMethodBuilder", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_void_method_builder.html", "struct_cysharp_1_1_threading_1_1_tasks_1_1_compiler_services_1_1_async_uni_task_void_method_builder" ]
];